baseurl: "" # The subpath of your site. Use "" if you're hosting a blog at the root level.
url: "EliasNP.github.io" # the base hostname & protocol for your site.

paginate: 6 #articles per page
paginate_path: /blog/page:num #makes pagination working

# header text
title: Blog de Eli@sN–ü  - üêß01
header: BASH where there is a shell, there is a way

# for welcome page
# to replace image go to index.html
email:
  address: "eliasnieva@keemail.me"
  text: "eliasnieva (at) keemail.me"

# disqus comment
disqus:
    shortname: "eliasnp.github.io" #your disqus comment short name

# google analytics
google:
    tracking-id: "" #your tracking id here

gems:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

# This is used by feed.xml. Uncomment if you want to use it.
# description: "..."

exclude:
  - "README.md"
  - "CHANGELOG.md"
  - "Gemfile"
  - "Gemfile.lock"

permalink: /posts/:title

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
